version: '3.8'

services:
  app:
    build: .
    image: task-management-system
    ports:
      - "3000:3000" 
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/taskmanagementsystem
    volumes:
      - .:/usr/src/app 
    depends_on:
      - mongo 

  mongo:
    image: mongo:latest
    container_name: task-management-system-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: task-management-system-test
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/taskmanagementsystem
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    command: npm test

volumes:
  mongo_data:
